// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLSoHoFwebyGvjJHgl_mRXwByiu53KsKY',
    appId: '1:21618207674:web:4e2a75b2c37a71cfbccb83',
    messagingSenderId: '21618207674',
    projectId: 'meteo-ba45f',
    authDomain: 'meteo-ba45f.firebaseapp.com',
    storageBucket: 'meteo-ba45f.firebasestorage.app',
    measurementId: 'G-LVTGBEVQW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmNsCVJLDGus5fCREhsgE7NpI6-0G6gnQ',
    appId: '1:21618207674:android:afa6b10bff50bb03bccb83',
    messagingSenderId: '21618207674',
    projectId: 'meteo-ba45f',
    storageBucket: 'meteo-ba45f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlXOIlTkIQ3xqEDnrXV-r9UgO9aGslwi0',
    appId: '1:21618207674:ios:2c95ce6abb01773abccb83',
    messagingSenderId: '21618207674',
    projectId: 'meteo-ba45f',
    storageBucket: 'meteo-ba45f.firebasestorage.app',
    iosBundleId: 'com.example.ecoflow',
  );
}
